### GET request to example server
GET http://localhost:8080/full

### POST token generation request
POST http://localhost:8080/generate-token
Content-Type: application/json

{
  "requests_per_second": 3
}

### GET request to example server
GET http://localhost:8080/full
API_KEY: bearer C18xgyupulegPa6FMmaQSwfbPg6Vlvdh

###


